### ISSUE TITLE
バーナム暗号とストリーム暗号

### ISSUE THREAD

**Issue by tetsu1008** [saitolaborg/mastering_tcpip_sec#1]
## ページ

67

## 記載内容

「バーナム暗号（62ページ参照）もストリーム暗号化方式ですが」

## 気付いた点

他のいくつかの書籍では、バーナム暗号とストリーム暗号は明確に使い分けられているように思います。具体的には、バーナム暗号は真の乱数列を用いる暗号、ストリーム暗号は疑似乱数列を用いる暗号の総称として説明されていることが多いようです。

以下の書籍で確認しました。

- [『暗号技術入門 第3版 秘密の国のアリス』 (hyuki.com)](https://www.hyuki.com/cr/)
- [図解即戦力 暗号と認証のしくみと理論がこれ1冊でしっかりわかる教科書：書籍案内｜技術評論社 (gihyo.jp)](https://gihyo.jp/book/2021/978-4-297-12307-9)
- [クラウドを支えるこれからの暗号技術 (herumi.github.io)](https://herumi.github.io/ango/)
- [徹底解剖 TLS 1.3（古城 隆 松尾 卓幸 宮崎 秀樹 須賀 葉子）｜翔泳社の本 (shoeisha.co.jp)](https://www.shoeisha.co.jp/book/detail/9784798171418)
  - バーナム暗号の説明はありませんが、ストリーム暗号では疑似乱数列を用いるとの説明があります。
- [セキュリティ技術の教科書　第2版 | IT資格試験の取得、IT人材育成は株式会社アイテック（iTEC）](https://www.itec.co.jp/store/products/detail.php?product_id=3436)
  - バーナム暗号の説明はありませんが、ストリーム暗号では疑似乱数列を用いるとの説明があります。

**Comment by saitolaborg** [comment]
修正案：
P.67（下から2行目）
「バーナム暗号 （62ページ参照）もストリーム暗号化方式ですが、」
→
「バーナム暗号 （62ページ参照）もストリーム暗号化方式と同様に乱数を用いますが、」

**Comment by saitolaborg** [comment]
2nd_ed_eratta.csv No. 13
