### ISSUE TITLE
3DESの利用

### ISSUE THREAD

**Issue by tetsu1008** [saitolaborg/mastering_tcpip_sec#2]
## ページ

69

## 記載内容

「3DESも、鍵を2種類使う方法は利用を避けることになっています」

## 気付いた点

現在は、鍵を3種類使う方法も利用を避けることになっていると思われます。NISTは2023年以降の利用禁止を表明し、CRYPTREC暗号リストでも運用監視暗号リストに分類されています。

## 参考

- [さらばDES暗号、2023年終了へカウントダウン | 日経クロステック（xTECH） (nikkei.com)](https://xtech.nikkei.com/atcl/nxt/column/18/00001/00986/)
- [Draft NIST SP 800-131A Rev. 2, Transitioning the Use of Cryptographic Algorithms and Key Lengths](https://csrc.nist.gov/CSRC/media/Publications/sp/800-131a/rev-2/draft/documents/sp800-131Ar2-draft.pdf)
- [CRYPTREC | CRYPTREC暗号リスト(電子政府推奨暗号リスト)](https://www.cryptrec.go.jp/list.html)

**Comment by saitolaborg** [comment]
修正案：
P.69 （最初の脚注）
＜最後に追記＞
「また、SP 800-131A Rev. 2（2019）にて、2023年以降、3-keyの3DESの利用を禁止した。」

**Comment by saitolaborg** [comment]
2nd_ed_eratta.csv No.12

**Comment by saitolaborg** [comment]
2nd_ed_eratta.csv No.12
