### ISSUE TITLE
MITM攻撃

### ISSUE THREAD

**Issue by tetsu1008** [saitolaborg/mastering_tcpip_sec#3]
## ページ

94

## 記載内容

「このように、攻撃者が通信に割り込んでメッセージを改ざんする攻撃をMITM攻撃と呼びます」

## 気付いた点

盗聴のみの場合でもMITM攻撃と呼ぶと思います。「盗聴もしくは改ざんする攻撃を」などとしたほうが適切だと感じました。

**Comment by saitolaborg** [comment]
修正案：
P.94 L.15
「このように、 攻撃者が通信に割り込んでメッセージを改ざんする  攻撃をMITM攻撃と呼びます。 」
→
「このように、攻撃者が通信に割り込んでメッセージを改ざんできてしまうことによりMITM攻撃が攻撃者の意図通りに成立してしまいます。 」
（MITMの説明をしたいわけではなく、ここでは、MITMが成立することを示している。）

**Comment by tetsu1008** [comment]
> （MITMの説明をしたいわけではなく、ここでは、MITMが成立することを示している。）

たしかにそうでした。こちらのissueは、かなり揚げ足取り的だったと思います。失礼いたしました。

元の文章のままでも特に問題はないと感じました。

**Comment by saitolaborg** [comment]
元のご指摘はその通りで、誤解を与える表記なので、修正しいます。

2nd_ed_eratta.csv No.11
