### ISSUE TITLE
MACの種類

### ISSUE THREAD

**Issue by tetsu1008** [saitolaborg/mastering_tcpip_sec#4]
## ページ

98

## 記載内容

（枠外：MACについての説明部分）

「Keying HashやHMAC（Hash-based Message Authentication Code）とも呼ばれる」

## 気付いた点

MACにはブロック暗号を用いるCMACも存在するので、文頭に「ハッシュ関数を用いるMACは」などと付けるほうが適切だと感じました。

**Comment by saitolaborg** [comment]
修正案：
P.98　（脚注の最後の文）
「Keying HashやHMAC（Hash-based Message Authentication Code）とも呼ばれる。 」
→
「MACの中でハッシュ関数を用いるものはKeying HashやHMAC（Hash-based Message Authentication Code）とも呼ばれることもある。 」

**Comment by saitolaborg** [comment]
2nd_ed_eratta.csv No. 17
