### ISSUE TITLE
ディジタル署名の概要

### ISSUE THREAD

**Issue by tetsu1008** [saitolaborg/mastering_tcpip_sec#5]
## ページ

99

## 記載内容

「ディジタル署名（digital signature）とは、メッセージに対するハッシュ値を秘密鍵で暗号化することで、メッセージの改ざん検知、および否認防止を実現するしくみのことです」

## 気付いた点

- こちらの説明だとRSAを用いた署名に限定されてしまうと思います。ここでは署名全般について説明しているはずなので、「メッセージに対するハッシュ値および署名用の秘密鍵を使用することで」などとするほうが適切だと感じました。
- 可能であれば、「署名の生成に用いる秘密鍵は、復号に用いる秘密鍵と区別するために『署名鍵』と呼ばれることもあります」や、「署名の検証に用いる公開鍵は、暗号化に用いる公開鍵と区別するために『検証鍵』と呼ばれることもあります」という記載があるとさらに親切だと感じました。
- 後に続く手順1～手順8の流れについては、RSAを用いる方式であることを明記すべきだと思います。DSAやECDSAの場合、ハッシュ値の一致を確認するわけではないため、ここで説明している手順とは異なるからです。

**Comment by saitolaborg** [comment]
修正案：
P.99 L.2
「ディジタル署名（digital signature）とは、メッセージに対するハッシュ値を秘密鍵で暗号化することで、メッセージの改ざん検知、および否認防止を実現するしくみのことです。」
→
「ディジタル署名（digital signature）とは、メッセージに対するハッシュ値および署名用の秘密鍵▼を使用することで、メッセージの改ざん検知、および否認防止を実現するしくみのことです。」

▼秘密鍵
ディジタル署名の生成に用いる秘密鍵は、復号に用いる秘密鍵と区別するために「署名鍵」とし、ディジタル署名の検証に用いる公開鍵は、暗号化に用いる公開鍵と区別するために「検証鍵」と呼ぶこともある。

P.99 L.10
「署名処理から検証処理までのディジタル署名の一連の流れは、以下のとおりです（図2.41）。」
→
「署名処理から検証処理までのRSAを用いるディジタル署名の一連の流れは、以下のとおりです（図2.41）。」

P.99 （2つ目の脚注の最後の文）
「本書では、便宜的に「暗号化」と表現する。」
→
（削除）

**Comment by saitolaborg** [comment]
2nd_ed_eratta.csv No.7 - 10
