### ISSUE TITLE
サーバー証明書の用途

### ISSUE THREAD

**Issue by tetsu1008** [saitolaborg/mastering_tcpip_sec#6]
## ページ

160

## 記載内容

「SSL/TLS通信における暗号化に必要な公開鍵などの情報を含み」

## 気付いた点

TLSにおいて、公開鍵が暗号化に使われる場面（具体的には静的RSAによる鍵交換）はなくなってきており、ほとんどは署名による認証に使われると思います。証明書が認証に使われることは直後の文で説明があるので、ここで単に「SSL/TLS通信において必要な公開鍵などの情報を含み」などとするほうが適切だと感じました。

**Comment by saitolaborg** [comment]
修正案：
P.16 L.6
「SSL/TLS通信における暗号化に必要な公開鍵などの情報を含み」
→
「SSL/TLS通信におけるディジタル署名に必要な公開鍵などの情報を含み」

**Comment by saitolaborg** [comment]
2nd_ed_eratta.csv No.6
