### ISSUE TITLE
証明書の検証方法

### ISSUE THREAD

**Issue by tetsu1008** [saitolaborg/mastering_tcpip_sec#7]
## ページ

164

## 記載内容

「ここでの検証とは真正性の検証であり、『署名前証明書のハッシュ値』と『証明書Cert1に含まれる署名を認証局Xの公開鍵で復号した値』を比較することです」

## 気付いた点

こちらの説明はECDSAには当てはまらないため、「署名アルゴリズムとしてRSAが用いられている場合には、」などの補足が必要だと感じました。

**Comment by saitolaborg** [comment]
修正案：
P.164 L.9　
「ここでの検証とは真正性の検証であり、『署名前証明書のハッシュ値』と『証明書Cert1に含まれる署名を認証局Xの公開鍵で復号した値』を比較することです」
→
「ここでの検証とは真正性の検証であり、『署名前証明書のハッシュ値』と『証明書Cert1に含まれる署名を認証局Xの公開鍵で検証処理で復元（RSAを用いた署名の場合、復号処理）した値』を比較することです」

**Comment by saitolaborg** [comment]
2nd_ed_eratta.csv No.5
