### ISSUE TITLE
セキュリティプロトコルの全体図

### ISSUE THREAD

**Issue by tetsu1008** [saitolaborg/mastering_tcpip_sec#8]
## ページ

173

## 記載内容

図5.1「セキュリティプロトコルとその目的」

## 気付いた点

- 「公開鍵暗号化技術」に「DSA、ECDSA」があり、「認証プロトコル」に「ディジタル署名」がありますが、DSAとECDSAはディジタル署名のアルゴリズムなので、これらが別々の枠に入っていることに違和感を覚えました。「認証プロトコル」には「ディジタル署名」ではなく「公開鍵認証」などと書くほうが適切ではないかと感じました。
- 図5.1の分類そのものにも違和感を覚えました。広義の「公開鍵暗号」（英語で言えばPublic Key Cryptography）には、公開鍵による暗号化（狭義の「公開鍵暗号」、英語で言えばPublic Key Encryption）、署名、鍵交換の3つが含まれると思います。そのため、鍵交換で枠を1つ用意するのであれば、署名に関しても別枠を用意するのが適切なのではないかと感じました。
  - 参考リンクにあるように、公開鍵による暗号化、署名、鍵交換を全て1つの「公開鍵暗号」という枠に入れる案もあると思いますが、本書でそれをする場合、「公開鍵暗号**化**」という枠に入れることになり、誤解を生んでしまう可能性があると思いました。
- 上記のようなことを考えていくと、実は本書では広義の「公開鍵暗号」と、「公開鍵による暗号化」の区別が曖昧であると気付きました。具体的には、本書で「公開鍵暗号化技術」と言ったときに、署名を含むか含まないかがページによって異なっています。たとえば、173ページの図5.1では署名は公開鍵暗号化技術に含まれていますが、177ページの図5.3では含まれていません。
  - 61ページの冒頭で「『暗号化アルゴリズム』と『暗号アルゴリズム』を使い分けます」と記載されているのですが、その後のページで考慮が漏れてしまっているように見受けられました。
  - 全体に渡って見直すとなると影響範囲が広くなってしまいますし、入門用の教科書としてどこまで厳密に記載するかということもあると思いますが……。
	
## 参考
- [あなたの「公開鍵暗号」はPKE? それともPKC? - Cybozu Inside Out | サイボウズエンジニアのブログ](https://blog.cybozu.io/entry/2021/12/28/080000)

**Comment by saitolaborg** [comment]
仰る通りですね。5.1の最初にセキュリティプロトコルの概要を掴むための説明を入れるのがよいだろうと、第二版で書いたのですが、他との整合性が取れていなかったですね。詳細に記載するとなると、概要を掴むためのという趣旨が崩れるので、ご指摘を踏まえて修正を考えたいと思います。もう少し考えます。

**Comment by saitolaborg** [comment]
修正案：
P.173　図5.1 （左下）「ディジタル署名」→「公開鍵を用いた認証」
P.177　図5.3「ハッシュ関数」→「メッセージ改竄検知」
P.177　図5.3「鍵共有アルゴリズム」→「鍵交換方式」
P.177　図5.3「ディジタル署名」→「認証プロトコル」

**Comment by tetsu1008** [comment]
P.177 図5.3 の変更は、P.173 図 5.1 に合わせているのですね！ダイナミックな変更に見えたので最初は驚きましたが、統一感があって良いなと感じました。

**Comment by saitolaborg** [comment]
2nd_ed_eratta.csv No. 14-17
