### ISSUE TITLE
TLS 1.3の暗号スイート

### ISSUE THREAD

**Issue by tetsu1008** [saitolaborg/mastering_tcpip_sec#9]
## ページ

196

## 記載内容

「TLS 1.3では、鍵交換の方式についてPFSの確保に問題があったアルゴリズム、RSA、ECDSA、DH、ECDHは廃止されました。また、鍵交換アルゴリズムはDHEとECDHEのみに限定されました」

## 気付いた点

- ECDSAは鍵交換のアルゴリズムではないので、ここに登場するのは不適切だと思います。また、2つの文に分かれていますが、どちらも鍵交換アルゴリズムについての記述なので、「TLS 1.3では、鍵交換の方式についてPFSの確保に問題があったアルゴリズム、RSA、DH、ECDHが廃止され、DHEとECDHEのみに限定されました」などとするのが適切だと感じました。
- TLS 1.3では署名アルゴリズムとしてDSAが廃止された点は記載しておくべきだと感じました。
- TLS 1.3の暗号スイートが5つになった背景として、「TLS 1.3の暗号スイートでは、共通鍵暗号化アルゴリズムとハッシュアルゴリズムのみを指定し、鍵交換アルゴリズムや署名アルゴリズムはTLS拡張で指定するように変更された」点も記載しておくべきだと感じました。

**Comment by saitolaborg** [comment]
仰る通りですね。ありがとうございます。ご提案の記述を参考にして、以下の通りに修正したいと思います。ご指摘は全て取り込んでいるかと思います。

P.196 L.19
「TLS 1.3では、鍵交換の方式についてPFSの確保に問題があったアルゴリズム、RSA、ECDSA、DH、ECDHは廃止されました。また、鍵交換アルゴリズムはDHEとECDHEのみに限定されました」
→
「TLS 1.3の暗号スイート（CipherSuitesフィールドにて指定）では、共通鍵暗号化アルゴリズムとハッシュアルゴリズムのみを指定することとなり、鍵交換アルゴリズムや署名アルゴリズムはExtensionsフィールドで指定することとなりました。また、鍵交換アルゴリズムについては、PFSの確保に問題がある（鍵交換として利用する）RSA、DH、および、ECDHが廃止され、TLS 1.3での鍵交換はDHEおよびECDHEのみに限定されました。なお、TLS 1.3では、DSAは廃止されました。」

**Comment by saitolaborg** [comment]
2nd_ed_eratta.csv, No.4
